config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  namespace :admin do
    resources :news_items, only: [:create, :update]
    get '/', to: 'news_items#new'
  end

  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/news_item.rb
class NewsItem < ApplicationRecord
  validates :title, :description, :expire_at, presence: true
  validate :check_expire_at

  def self.current
    find_by("expire_at > ?", Time.current)
  end

  private

  def check_expire_at
    if expire_at && expire_at.beginning_of_minute < Time.now.beginning_of_minute
      errors.add(:expire_at, 'Не может быть меньше текущего времени')
    end
  end
end

app/models/yandex_news_item.rb
class YandexNewsItem
  attr_accessor :title, :description, :created_at

  def self.current
    yandex_news = YandexNewsService.new.perform
    item = self.new
    item.title = yandex_news[:title]
    item.description = yandex_news[:description]
    item.created_at = yandex_news[:created_at]

    item
  end
end

app/controllers/admin/news_items_controller.rb
class Admin::NewsItemsController < ApplicationController
  def new
    @item = current_item || NewsItem.new(expire_at: Time.now)
  end

  def create
    @item = NewsItem.new(permit_params)

    if @item.save
      item_news_job(@item)
      redirect_to admin_path
    else
      render 'new'
    end
  end

  def update
    @item = current_item
    if @item && @item.update(permit_params)
      item_news_job(@item)
      redirect_to admin_path
    elsif !@item
      redirect_to admin_path
    else
      render 'new'
    end
  end

  private

  def current_item
    NewsItem.current
  end

  def item_news_job(item)
    ::NewsItemBroadcastJob.perform_later(item)
    ::NewsItemBroadcastJob.set(wait: item.expire_at - Time.now).perform_later
  end

  def permit_params
    params.require(:news_item).permit(:title, :description, :expire_at)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @item = NewsItem.current || YandexNewsItem.current
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/news_items/new.slim
- url = @item.new_record? ? admin_news_items_path : admin_news_item_path(@item)
= semantic_form_for @item, url: url do |f| 
  = f.inputs name: "Новость на главной" do
    = f.input :title, input_html: { class: 'form-control' }
    = f.input :description, as: :text, input_html: { class: 'form-control', rows: 4 }
    .row
      .col-md-4
        = f.input :expire_at, as: :datetime_picker, input_html: { class: 'form-control' }
    = f.action :submit, label: 'Сохранить', button_html: { class: 'btn btn-success' }

app/views/home/index.slim
h1 Breaking news
br
#container= render 'news_items/item', item: @item

app/views/layouts/application.slim
doctype html

html
  head
    title NewsApp
    = csrf_meta_tags

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body
    .container
      = yield

app/views/news_items/_item.slim
.news__container
  .row
    .col-md-2
      .news__date= item.created_at.strftime('%d-%m-%Y %H:%M')
    .col-md-10
      h4.news__title= item.title
      .news__description
        =item.description.html_safe